remote_theme: pages-themes/cayman@v0.2.0
title: Розробка програмного забезпечення
## Тема вашої дипломної роботи
Кваліфікаційна робота на підтвердження ступеня фахового молодшого
бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)).
Керівник роботи – Ковальова Наталія Володимирівна.
description: Дипломна робота Герасименка М.О.
## Завдання до дипломної роботи
Web-ресурс для інтернет-магазину з продажу електроніки
